apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: hirodevops04/hello-app
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl:
    manifests:
      - hello*
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: jx-test-2020110302
        chartPath: charts/jx-test-2020110302
        setValueTemplates:
          image.repository: hirodevops04
          image.tag: hello-app:latest
